document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>花朵绽放(较为卡顿)</title>");
document.writeln("");
document.writeln("    <style>");
document.writeln("    HTML, BODY { height: 100%; overflow: hidden; }");
document.writeln("    BODY { background: #0a0a0a; background-image: -webkit-linear-gradient(#0f0f0f 1px, transparent 1px), -webkit-linear-gradient(left, #0f0f0f 1px, transparent 1px); background-image: linear-gradient(#0f0f0f 1px, transparent 1px), linear-gradient(to right, #0f0f0f 1px, transparent 1px); background-size: 3.33333vmin 3.33333vmin; }");
document.writeln("    .range { /* display: none; */");
document.writeln("    position: absolute; zind: 2px; }");
document.writeln("    .wrapper { position: absolute; top: 0; right: 0; bottom: 0; left: 0; margin: auto; width: 10vmin; height: 10vmin; font-size: 10vmin; -webkit-transform: rotateX(-45deg); transform: rotateX(-45deg); -webkit-transform-style: preserve-3d; transform-style: preserve-3d; }");
document.writeln("    .flower { width: 10vmin; height: 10vmin; -webkit-animation: rotate-flower 10s linear infinite; animation: rotate-flower 10s linear infinite; -webkit-transform-style: preserve-3d; transform-style: preserve-3d; }");
document.writeln("    .flower:before { content: \'\'; display: block; position: absolute; width: 95%; height: 95%; top: 0; right: 0; bottom: 0; left: 0; margin: auto; background: #226600; border-radius: 50%; -webkit-transform: rotateX(90deg); transform: rotateX(90deg); -webkit-animation: rotate-hue 5s infinite; animation: rotate-hue 5s infinite; }");
document.writeln("    .petal { position: absolute; z-index: 20; bottom: 80%; left: -10vmin; -webkit-transform-style: preserve-3d; transform-style: preserve-3d; -webkit-transform-origin: bottom; transform-origin: bottom; }");
document.writeln("    .box { width: 30vmin; -webkit-transform-style: preserve-3d; transform-style: preserve-3d; -webkit-transform-origin: bottom; transform-origin: bottom; -webkit-animation: rotate-box 12s infinite; animation: rotate-box 12s infinite; }");
document.writeln("    .shape { width: 0.5em; height: 0.5em; margin: auto; background: currentColor; box-shadow: 0.5em 0 0 0, 1em 0 0 0, -1em 0 0 0, -0.5em 0 0 0; border-radius: 50%; -webkit-animation: rotate-hue 5s infinite; animation: rotate-hue 5s infinite; }");
document.writeln("    @-webkit-keyframes rotate-box {");
document.writeln("    0% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    15% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    50% {");
document.writeln("    -webkit-transform: rotateX(-7deg);");
document.writeln("    transform: rotateX(-7deg);");
document.writeln("    }");
document.writeln("    80% {");
document.writeln("    -webkit-transform: rotateX(-7deg);");
document.writeln("    transform: rotateX(-7deg);");
document.writeln("    }");
document.writeln("    100% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("    @keyframes rotate-box {");
document.writeln("    0% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    15% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    50% {");
document.writeln("    -webkit-transform: rotateX(-7deg);");
document.writeln("    transform: rotateX(-7deg);");
document.writeln("    }");
document.writeln("    80% {");
document.writeln("    -webkit-transform: rotateX(-7deg);");
document.writeln("    transform: rotateX(-7deg);");
document.writeln("    }");
document.writeln("    100% {");
document.writeln("    -webkit-transform: rotateX(3.5deg);");
document.writeln("    transform: rotateX(3.5deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("    @-webkit-keyframes rotate-flower {");
document.writeln("    100% {");
document.writeln("    -webkit-transform: rotateY(360deg);");
document.writeln("    transform: rotateY(360deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("    @keyframes rotate-flower {");
document.writeln("    100% {");
document.writeln("    -webkit-transform: rotateY(360deg);");
document.writeln("    transform: rotateY(360deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("    @-webkit-keyframes rotate-hue {");
document.writeln("    100% {");
document.writeln("    -webkit-filter: hue-rotate(360deg);");
document.writeln("    filter: hue-rotate(360deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("    @keyframes rotate-hue {");
document.writeln("    100% {");
document.writeln("    -webkit-filter: hue-rotate(360deg);");
document.writeln("    filter: hue-rotate(360deg);");
document.writeln("    }");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Demo Buttons Style */");
document.writeln("    .codrops-demos {");
document.writeln("        font-size: 0.8em;");
document.writeln("        text-align:center;");
document.writeln("        position:absolute;");
document.writeln("        z-index:99;");
document.writeln("        width:96%;");
document.writeln("    }");
document.writeln("");
document.writeln("    .codrops-demos a {");
document.writeln("        display: inline-block;");
document.writeln("        margin: 0.35em 0.1em;");
document.writeln("        padding: 0.5em 1.2em;");
document.writeln("        outline: none;");
document.writeln("        text-decoration: none;");
document.writeln("        text-transform: uppercase;");
document.writeln("        letter-spacing: 1px;");
document.writeln("        font-weight: 700;");
document.writeln("        border-radius: 2px;");
document.writeln("        font-size: 110%;");
document.writeln("        border: 2px solid transparent;");
document.writeln("        color:#fff;");
document.writeln("    }");
document.writeln("");
document.writeln("    .codrops-demos a:hover,");
document.writeln("    .codrops-demos a.current-demo {");
document.writeln("        border-color: #383a3c;");
document.writeln("    }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    ");
document.writeln("    <div class=\'wrapper\'>");
document.writeln("        <div class=\'flower\'></div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("<script>");
document.writeln("     console.clear();");
document.writeln("");
document.writeln("var doc = document;");
document.writeln("var flower = doc.querySelector(\'.flower\');");
document.writeln("var range = doc.querySelector(\'.range\');");
document.writeln("");
document.writeln("var petalPartMarkup = \'<div class=\'box\'> \/\/");
document.writeln("                    <div class=\'shape\'></div> \/\/");
document.writeln("                </div>\';");
document.writeln("");
document.writeln("var maxParts = 20;");
document.writeln("var maxPetalsDef = 6;");
document.writeln("var maxPetals = maxPetalsDef;");
document.writeln("");
document.writeln("var partsFontStepDef = 25 / maxParts;");
document.writeln("var partsFontStep = partsFontStepDef;");
document.writeln("var huetStep = 150 / maxParts;");
document.writeln("");
document.writeln("createFlower();");
document.writeln("");
document.writeln("function createFlower() {");
document.writeln("");
document.writeln("	var angle = 360 / maxPetals;");
document.writeln("");
document.writeln("	for (var i = 0; i < maxPetals; i++) {");
document.writeln("		var petal = createPetal();");
document.writeln("		var currAngle = angle * i + \'deg\';");
document.writeln("		var transform = \'transform: rotateY(\' + currAngle + \') rotateX(-30deg) translateZ(9vmin)\';");
document.writeln("");
document.writeln("		petal.setAttribute(\'style\', transform);");
document.writeln("");
document.writeln("		flower.appendChild(petal);");
document.writeln("	}");
document.writeln("}");
document.writeln("");
document.writeln("function createPetal() {");
document.writeln("");
document.writeln("	var box = createBox(null, 0);");
document.writeln("");
document.writeln("	var petal = doc.createElement(\'div\');");
document.writeln("	petal.classList.add(\'petal\');");
document.writeln("");
document.writeln("	for (var i = 1; i <= maxParts; i++) {");
document.writeln("		newBox = createBox(box, i);");
document.writeln("		box = newBox;");
document.writeln("	}");
document.writeln("");
document.writeln("	petal.appendChild(box);");
document.writeln("");
document.writeln("	return petal;");
document.writeln("}");
document.writeln("");
document.writeln("function createBox(box, pos) {");
document.writeln("");
document.writeln("	var fontSize = partsFontStep * (maxParts - pos) + \'vmin\';");
document.writeln("	var half = maxParts / 2;");
document.writeln("");
document.writeln("	var bright = \'50\';");
document.writeln("");
document.writeln("	if (pos < half + 1) {");
document.writeln("		fontSize = partsFontStep * pos + \'vmin\';");
document.writeln("	} else {");
document.writeln("		bright = 10 + 40 / half * (maxParts - pos);");
document.writeln("	}");
document.writeln("");
document.writeln("	var color = \'hsl(\' + huetStep * pos + \', 100%, \' + bright + \'%)\';");
document.writeln("");
document.writeln("	// 1. Add shape");
document.writeln("	var newShape = doc.createElement(\'div\');");
document.writeln("	newShape.classList.add(\'shape\');");
document.writeln("");
document.writeln("	// 2. Create wrapper .box");
document.writeln("	var newBox = doc.createElement(\'div\');");
document.writeln("	newBox.classList.add(\'box\');");
document.writeln("");
document.writeln("	var boxStyle = [\'color: \' + color, \'font-size: \' + fontSize].join(\';\');");
document.writeln("	newBox.setAttribute(\'style\', boxStyle);");
document.writeln("");
document.writeln("	// 3. Add old box to new box");
document.writeln("	if (box) {");
document.writeln("		newBox.appendChild(box);");
document.writeln("	}");
document.writeln("");
document.writeln("	// 4. Add shape to new box");
document.writeln("	newBox.appendChild(newShape);");
document.writeln("");
document.writeln("	return newBox;");
document.writeln("}");
document.writeln("");
document.writeln("function out(content) {");
document.writeln("	console.log(content);");
document.writeln("}");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");