document.writeln("<!-- 依赖JQuery -->");
document.writeln("<!-- 依赖JQuery -->");
document.writeln("<!-- 依赖JQuery -->");
document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>在海里(鼠标移动可以切换鱼)</title>");
document.writeln("");
document.writeln("    <!-- 依赖JQuery -->");
document.writeln("    <script src=\'https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js\'></script>");
document.writeln("    <!-- END -->");
document.writeln("");
document.writeln("    <style>");
document.writeln("    html,body {");
document.writeln("        width: 100%;");
document.writeln("        height: 100%;");
document.writeln("        margin: 0;");
document.writeln("        padding: 0;");
document.writeln("        overflow: hidden;");
document.writeln("    }");
document.writeln("    .container{");
document.writeln("        position: relative;");
document.writeln("        width: 100%;");
document.writeln("        height: 100%;");
document.writeln("        margin: 0;");
document.writeln("        padding: 0;");
document.writeln("    }");
document.writeln("    canvas{");
document.writeln("        position: absolute;");
document.writeln("        top: 0;");
document.writeln("        left: 0;");
document.writeln("    }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("    <div id=\'jsi-sea-container\' class=\'container\'>");
document.writeln("        <canvas width=\'1920\' height=\'950\'></canvas>");
document.writeln("        <canvas width=\'1920\' height=\'950\'></canvas>");
document.writeln("    </div>");
document.writeln("");
document.writeln("<script>");
document.writeln("var HAMMERHEAD_RENDERER = {");
document.writeln("	HAMMERHEAD_COUNT : 10,");
document.writeln("	ADD_INTERVAL : 3,");
document.writeln("	DELTA_THETA : Math.PI / 1000,");
document.writeln("	ADJUST_DISTANCE : 50,");
document.writeln("	ADJUST_OFFSET : 10,");
document.writeln("	");
document.writeln("	init : function(){");
document.writeln("		this.setParameters();");
document.writeln("		this.reconstructMethod();");
document.writeln("		this.createHammerHeads(this.INIT_HAMMERHEAD_COUNT);");
document.writeln("		this.bindEvent();");
document.writeln("		this.render();");
document.writeln("	},");
document.writeln("	setParameters : function(){");
document.writeln("		this.$window = $(window);");
document.writeln("		this.$container = $(\'#jsi-sea-container\');");
document.writeln("		this.width = this.$container.width();");
document.writeln("		this.height = this.$container.height();");
document.writeln("		this.context = $(\'<canvas />\').attr({width : this.width, height : this.height}).appendTo(this.$container).get(0).getContext(\'2d\');");
document.writeln("		this.interval = this.ADD_INTERVAL;");
document.writeln("		this.distance = Math.sqrt(Math.pow(this.width / 2, 2) + Math.pow(this.height / 2, 2));");
document.writeln("		this.x =  this.width;");
document.writeln("		this.destinationX = this.x;");
document.writeln("		this.theta = 0;");
document.writeln("		this.hammerheads = [];");
document.writeln("	},");
document.writeln("	reconstructMethod : function(){");
document.writeln("		this.render = this.render.bind(this);");
document.writeln("	},");
document.writeln("	createHammerHeads : function(){");
document.writeln("		for(var i = 0, length = this.HAMMERHEAD_COUNT; i < length; i++){");
document.writeln("			this.hammerheads.push(new HAMMERHEAD(this.width, this.height));");
document.writeln("		}");
document.writeln("	},");
document.writeln("	bindEvent : function(){");
document.writeln("		this.$container.on(\'mousemove\', this.changeView.bind(this, false));");
document.writeln("		this.$container.on(\'mouseout\', this.changeView.bind(this, true));");
document.writeln("	},");
document.writeln("	changeView : function(toAdjust, event){");
document.writeln("		this.destinationX = event.clientX - this.$container.offset().left + this.$window.scrollLeft();");
document.writeln("		");
document.writeln("		if(!toAdjust){");
document.writeln("			return;");
document.writeln("		}");
document.writeln("		if(this.destinationX < this.ADJUST_OFFSET){");
document.writeln("			this.destinationX = 0;");
document.writeln("		}else if(this.distanceX > this.width - this.ADJUST_OFFSET){");
document.writeln("			this.destinationX = this.width;");
document.writeln("		}");
document.writeln("	},");
document.writeln("	render : function(){");
document.writeln("		requestAnimationFrame(this.render);");
document.writeln("		");
document.writeln("		var gradient = this.context.createRadialGradient(this.width / 2, this.height / 2, 0, this.width / 2, this.height / 2, this.distance),");
document.writeln("			rate = (1 + 0.2 * Math.sin(this.theta));");
document.writeln("			");
document.writeln("		gradient.addColorStop(0, \'hsl(195, 80%, \' + (90 * rate) + \'%)\');");
document.writeln("		gradient.addColorStop(0.2, \'hsl(195, 100%, \' + (50 * rate) + \'%)\');");
document.writeln("		gradient.addColorStop(1, \'hsl(220, 100%, \' + (10 * rate) + \'%)\');");
document.writeln("		");
document.writeln("		this.context.fillStyle = gradient;");
document.writeln("		this.context.fillRect(0, 0, this.width, this.height);");
document.writeln("		");
document.writeln("		this.hammerheads.sort(function(hammerhead1, hammerhead2){");
document.writeln("			return hammerhead1.z - hammerhead2.z;");
document.writeln("		});");
document.writeln("		for(var i = this.hammerheads.length - 1; i >= 0; i--){");
document.writeln("			if(!this.hammerheads[i].render(this.context)){");
document.writeln("				this.hammerheads.splice(i, 1);");
document.writeln("			}");
document.writeln("		}");
document.writeln("		this.context.clearRect(this.x, 0, this.width - this.x, this.height);");
document.writeln("		");
document.writeln("		if(this.interval-- == 0){");
document.writeln("			this.interval = this.ADD_INTERVAL;");
document.writeln("			this.hammerheads.push(new HAMMERHEAD(this.width, this.height));");
document.writeln("		}");
document.writeln("		this.theta += this.DELTA_THETA;");
document.writeln("		this.theta %= Math.PI * 2;");
document.writeln("		");
document.writeln("		if(this.destinationX > this.x){");
document.writeln("			this.x = Math.min(this.x + this.ADJUST_DISTANCE, this.destinationX);");
document.writeln("		}else{");
document.writeln("			this.x = Math.max(this.x - this.ADJUST_DISTANCE, this.destinationX);");
document.writeln("		}");
document.writeln("	}");
document.writeln("};");
document.writeln("var HAMMERHEAD = function(width, height){");
document.writeln("	this.width = width;");
document.writeln("	this.height = height;");
document.writeln("	this.init();");
document.writeln("};");
document.writeln("HAMMERHEAD.prototype = {");
document.writeln("	COLOR : \'hsl(220, %s%, 30%)\',");
document.writeln("	ANGLE_RANGE : {min : -Math.PI / 8, max : Math.PI / 8},");
document.writeln("	INIT_SCALE : 0.1,");
document.writeln("	MAX_Z : 10,");
document.writeln("	DELTA_PHI : Math.PI / 80,");
document.writeln("	VELOCITY : 3,");
document.writeln("	VERTICAL_THRESHOLD : 80,");
document.writeln("	");
document.writeln("	init : function(){");
document.writeln("		this.theta = this.ANGLE_RANGE.min + (this.ANGLE_RANGE.max - this.ANGLE_RANGE.min) * Math.random();");
document.writeln("		this.x = this.width / 2 + this.width / 4 * this.theta / Math.PI * 8;");
document.writeln("		this.y = this.height + this.VERTICAL_THRESHOLD * this.INIT_SCALE;");
document.writeln("		this.z = Math.random() * this.MAX_Z;");
document.writeln("		this.vx = -this.VELOCITY * Math.cos(this.theta + Math.PI / 2);");
document.writeln("		this.vy = -this.VELOCITY * Math.sin(this.theta + Math.PI / 2);");
document.writeln("		");
document.writeln("		this.phi = Math.PI * 2 * Math.random();");
document.writeln("		this.color = this.COLOR.replace(\'%s\', 90 - 60 * this.z / this.MAX_Z | 0);");
document.writeln("	},");
document.writeln("	render : function(context){");
document.writeln("		var tailX = 20 * Math.sin(this.phi),");
document.writeln("			angle = Math.sin(this.phi),");
document.writeln("			height = this.height + this.VERTICAL_THRESHOLD,");
document.writeln("			scale = this.INIT_SCALE + (1 - this.INIT_SCALE) * (height - this.y) / height * (this.MAX_Z - this.z) / this.MAX_Z;");
document.writeln("			");
document.writeln("		context.save();");
document.writeln("		context.fillStyle = this.color;");
document.writeln("		context.translate(this.x, this.y);");
document.writeln("		context.scale(scale, scale);");
document.writeln("		context.rotate(this.theta);");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo(-20, -40);");
document.writeln("		context.bezierCurveTo(-8, -48, 8, -48, 20, -40);");
document.writeln("		context.lineTo(20, -28);");
document.writeln("		context.lineTo(8, -36);");
document.writeln("		context.lineTo(8, -8);");
document.writeln("		context.lineTo(20, 4 + 6 * angle);");
document.writeln("		context.lineTo(8, 0);");
document.writeln("		context.lineTo(6, 16);");
document.writeln("		context.quadraticCurveTo(4, 32, tailX, 64);");
document.writeln("		context.quadraticCurveTo(-4, 32, -6, 16);");
document.writeln("		context.lineTo(-8, 0);");
document.writeln("		context.lineTo(-20, 4 - 6 * angle);");
document.writeln("		context.lineTo(-8, -8);");
document.writeln("		context.lineTo(-8, -36);");
document.writeln("		context.lineTo(-20, -28);");
document.writeln("		context.closePath();");
document.writeln("		context.fill();");
document.writeln("		");
document.writeln("		context.save();");
document.writeln("		context.beginPath();");
document.writeln("		context.translate(tailX, 64);");
document.writeln("		context.rotate(-Math.sin(this.phi) * Math.PI / 6);");
document.writeln("		context.moveTo(0, -5);");
document.writeln("		context.lineTo(10, 15);");
document.writeln("		context.lineTo(0, 5);");
document.writeln("		context.lineTo(-10, 15);");
document.writeln("		context.closePath();");
document.writeln("		context.fill();");
document.writeln("		context.restore();");
document.writeln("		context.restore();");
document.writeln("		");
document.writeln("		this.x += this.vx * scale;");
document.writeln("		this.y += this.vy * scale;");
document.writeln("		this.phi += this.DELTA_PHI;");
document.writeln("		this.phi %= Math.PI * 2;");
document.writeln("		");
document.writeln("		return this.y >= -this.VERTICAL_THRESHOLD;");
document.writeln("	}");
document.writeln("};");
document.writeln("var MANTA_RENDERER = {");
document.writeln("	MANTA_COUNT : 3,");
document.writeln("	ADD_INTERVAL : 30,");
document.writeln("	DELTA_THETA : Math.PI / 1000,");
document.writeln("	");
document.writeln("	init : function(){");
document.writeln("		this.setParameters();");
document.writeln("		this.reconstructMethod();");
document.writeln("		this.createMantas();");
document.writeln("		this.render();");
document.writeln("	},");
document.writeln("	setParameters : function(){");
document.writeln("		this.$container = $(\'#jsi-sea-container\');");
document.writeln("		this.width = this.$container.width();");
document.writeln("		this.height = this.$container.height();");
document.writeln("		this.context = $(\'<canvas />\').attr({width : this.width, height : this.height}).appendTo(this.$container).get(0).getContext(\'2d\');");
document.writeln("		this.interval = this.ADD_INTERVAL;");
document.writeln("		this.distance = Math.sqrt(Math.pow(this.width / 2, 2) + Math.pow(this.height / 2, 2));");
document.writeln("		this.theta = 0;");
document.writeln("		this.mantas = [];");
document.writeln("	},");
document.writeln("	reconstructMethod : function(){");
document.writeln("		this.render = this.render.bind(this);");
document.writeln("	},");
document.writeln("	createMantas : function(){");
document.writeln("		for(var i = 0, length = this.MANTA_COUNT; i < length; i++){");
document.writeln("			this.mantas.push(new MANTA(this.width, this.height, this.context));");
document.writeln("		}");
document.writeln("	},");
document.writeln("	render : function(){");
document.writeln("		requestAnimationFrame(this.render);");
document.writeln("		");
document.writeln("		var gradient = this.context.createRadialGradient(this.width / 2, this.height / 2, 0, this.width / 2, this.height / 2, this.distance),");
document.writeln("			rate = (1 + 0.2 * Math.sin(this.theta));");
document.writeln("			");
document.writeln("		gradient.addColorStop(0, \'hsl(195, 80%, \' + (60 * rate) + \'%)\');");
document.writeln("		gradient.addColorStop(0.2, \'hsl(195, 100%, \' + (40 * rate) + \'%)\');");
document.writeln("		gradient.addColorStop(1, \'hsl(220, 100%, \' + (5 * rate) + \'%)\');");
document.writeln("		");
document.writeln("		this.context.fillStyle = gradient;");
document.writeln("		this.context.fillRect(0, 0, this.width, this.height);");
document.writeln("		");
document.writeln("		this.mantas.sort(function(manta1, manta2){");
document.writeln("			return manta1.z - manta2.z;");
document.writeln("		});");
document.writeln("		for(var i = this.mantas.length - 1; i >= 0; i--){");
document.writeln("			if(!this.mantas[i].render(this.context)){");
document.writeln("				this.mantas.splice(i, 1);");
document.writeln("			}");
document.writeln("		}");
document.writeln("		if(this.interval-- == 0){");
document.writeln("			this.interval = this.ADD_INTERVAL;");
document.writeln("			this.mantas.push(new MANTA(this.width, this.height, this.context));");
document.writeln("		}");
document.writeln("		this.theta += this.DELTA_THETA;");
document.writeln("		this.theta %= Math.PI * 2;");
document.writeln("	}");
document.writeln("};");
document.writeln("var MANTA = function(width, height, context){");
document.writeln("	this.width = width;");
document.writeln("	this.height = height;");
document.writeln("	this.init(context);");
document.writeln("};");
document.writeln("MANTA.prototype = {");
document.writeln("	COLOR : \'hsl(200, %s%, %l%)\',");
document.writeln("	ANGLE_RANGE : {min : -Math.PI / 8, max : Math.PI / 8},");
document.writeln("	INIT_SCALE : 0.3,");
document.writeln("	RANGE_Z : {min : 0, max : 30},");
document.writeln("	DELTA_ANGLE : Math.PI / 160,");
document.writeln("	VELOCITY : 2,");
document.writeln("	VERTICAL_THRESHOLD : 400,");
document.writeln("	");
document.writeln("	init : function(context){");
document.writeln("		this.angle = this.getRandomValue(this.ANGLE_RANGE);");
document.writeln("		this.x = this.width / 2 + this.width / 3 * this.angle / Math.PI * 8;");
document.writeln("		this.y = this.height + this.VERTICAL_THRESHOLD * this.INIT_SCALE;");
document.writeln("		this.z = this.getRandomValue(this.RANGE_Z);");
document.writeln("		this.vx = -this.VELOCITY * Math.cos(this.angle + Math.PI / 2);");
document.writeln("		this.vy = -this.VELOCITY * Math.sin(this.angle + Math.PI / 2);");
document.writeln("		this.phi = Math.PI * 2 * Math.random();");
document.writeln("		this.theta = Math.PI * 2 * Math.random();");
document.writeln("		this.psi = Math.PI * 2 * Math.random();");
document.writeln("		");
document.writeln("		var color = this.COLOR.replace(\'%s\', 60),");
document.writeln("			luminance = 20 * this.z / this.RANGE_Z.max | 0;");
document.writeln("		");
document.writeln("		this.gradient = context.createLinearGradient(-140, 0, 140, 0);");
document.writeln("		this.gradient.addColorStop(0, color.replace(\'%l\', 10 + luminance));");
document.writeln("		this.gradient.addColorStop(0.1, color.replace(\'%l\', 10 + luminance));");
document.writeln("		this.gradient.addColorStop(0.5, color.replace(\'%l\', 20 + luminance));");
document.writeln("		this.gradient.addColorStop(0.9, color.replace(\'%l\', 10 + luminance));");
document.writeln("		this.gradient.addColorStop(1, color.replace(\'%l\', 10 + luminance));");
document.writeln("		this.color = this.COLOR.replace(\'%s\', 100).replace(\'%l\', 5 + luminance);");
document.writeln("	},");
document.writeln("	getRandomValue : function(range){");
document.writeln("		return range.min + (range.max - range.min) * Math.random();");
document.writeln("	},");
document.writeln("	render : function(context){");
document.writeln("		var height = this.height + this.VERTICAL_THRESHOLD,");
document.writeln("			scale = this.INIT_SCALE + (1 - this.INIT_SCALE) * (height - this.y) / height * (this.RANGE_Z.max - this.z) / this.RANGE_Z.max * 2,");
document.writeln("			top = (Math.sin(this.phi) < 0 ? 50 : 60) * Math.sin(this.phi);");
document.writeln("			");
document.writeln("		context.save();");
document.writeln("		context.translate(this.x, this.y);");
document.writeln("		context.scale(scale, scale);");
document.writeln("		context.rotate(this.angle);");
document.writeln("		");
document.writeln("		context.fillStyle = this.color;");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo((225 + top) / 4, -20);");
document.writeln("		context.lineTo((210 + top) / 4, 70 / 4);");
document.writeln("		context.lineTo(-(210 + top) / 4, 70 / 4);");
document.writeln("		context.lineTo(-(225 + top) / 4, -20);");
document.writeln("		context.closePath();");
document.writeln("		context.fill();");
document.writeln("		");
document.writeln("		context.lineWidth = 5;");
document.writeln("		context.strokeStyle = this.gradient;");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo(0, 70);");
document.writeln("		context.quadraticCurveTo(0, 130, 20 * Math.sin(this.theta), 190);");
document.writeln("		context.stroke();");
document.writeln("		");
document.writeln("		context.fillStyle = this.gradient;");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo(-15, -40);");
document.writeln("		context.bezierCurveTo(-10, -35, 10, -35, 15, -40);");
document.writeln("		context.lineTo(30, -40);");
document.writeln("		context.quadraticCurveTo(35, -40, 45, -30);");
document.writeln("		context.quadraticCurveTo(50, -25, 80 + top, 0);");
document.writeln("		context.quadraticCurveTo(60, 0, 10, 70);");
document.writeln("		context.lineTo(-10, 70);");
document.writeln("		context.quadraticCurveTo(-60, 0, -80 - top, 0);");
document.writeln("		context.quadraticCurveTo(-50, -25, -45, -30);");
document.writeln("		context.quadraticCurveTo(-35, -40, -30, -40);");
document.writeln("		context.lineTo(-15, -40);");
document.writeln("		context.closePath();");
document.writeln("		context.fill();");
document.writeln("		");
document.writeln("		context.lineWidth = 12;");
document.writeln("		context.strokeStyle = this.gradient;");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo(23, -38);");
document.writeln("		context.quadraticCurveTo(33, -55, 23 - 10 * Math.sin(this.psi), -70);");
document.writeln("		context.stroke();");
document.writeln("		");
document.writeln("		context.beginPath();");
document.writeln("		context.moveTo(-23, -38);");
document.writeln("		context.quadraticCurveTo(-33, -55, -23 + 10 * Math.sin(this.psi), -70);");
document.writeln("		context.stroke();");
document.writeln("		");
document.writeln("		context.lineWidth = 1;");
document.writeln("		context.strokeStyle = this.color;");
document.writeln("		context.beginPath();");
document.writeln("		");
document.writeln("		for(var i = 0; i < 5; i++){");
document.writeln("			var y = -10 + i * 8 + (1 - Math.sin(this.phi)) * 3;");
document.writeln("			context.moveTo(10, -20 + i * 8);");
document.writeln("			context.quadraticCurveTo(20, -15 + i * 8, 30, y);");
document.writeln("			context.moveTo(-10, -20 + i * 8);");
document.writeln("			context.quadraticCurveTo(-20, -15 + i * 8, -30, y);");
document.writeln("		}");
document.writeln("		context.stroke();");
document.writeln("		context.restore();");
document.writeln("		");
document.writeln("		this.x += this.vx * scale;");
document.writeln("		this.y += this.vy * scale;");
document.writeln("		this.phi += this.DELTA_ANGLE;");
document.writeln("		this.phi %= Math.PI * 2;");
document.writeln("		this.theta += this.DELTA_ANGLE;");
document.writeln("		this.theta %= Math.PI * 2;");
document.writeln("		this.psi += this.DELTA_ANGLE;");
document.writeln("		this.psi %= Math.PI * 2;");
document.writeln("		");
document.writeln("		return this.y >= -this.VERTICAL_THRESHOLD;");
document.writeln("	}");
document.writeln("};");
document.writeln("$(function(){");
document.writeln("	MANTA_RENDERER.init();");
document.writeln("	HAMMERHEAD_RENDERER.init();");
document.writeln("});");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");