document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>HTML5 Canvas矩阵粒子波浪背景动画特效</title>");
document.writeln("");
document.writeln("<style>");
document.writeln("html,body {");
document.writeln("	height:100%;");
document.writeln("}");
document.writeln("body {");
document.writeln("	margin:0;");
document.writeln("	background:#000;");
document.writeln("}");
document.writeln("canvas {");
document.writeln("	display:block;");
document.writeln("}");
document.writeln(".waves {");
document.writeln("	position:absolute;");
document.writeln("	left:0;");
document.writeln("	top:0;");
document.writeln("	right:0;");
document.writeln("	bottom:0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=\'waves\'></div>");
document.writeln("");
document.writeln("<script>");
document.writeln("class ShaderProgram {");
document.writeln("");
document.writeln("  constructor( holder, options = {} ) {");
document.writeln("");
document.writeln("    options = Object.assign( {");
document.writeln("      antialias: false,");
document.writeln("      depthTest: false,");
document.writeln("      mousemove: false,");
document.writeln("      autosize: true,");
document.writeln("      side: \'front\',");
document.writeln("      vertex: `");
document.writeln("        precision highp float;");
document.writeln("");
document.writeln("        attribute vec4 a_position;");
document.writeln("        attribute vec4 a_color;");
document.writeln("");
document.writeln("        uniform float u_time;");
document.writeln("        uniform vec2 u_resolution;");
document.writeln("        uniform vec2 u_mousemove;");
document.writeln("        uniform mat4 u_projection;");
document.writeln("");
document.writeln("        varying vec4 v_color;");
document.writeln("");
document.writeln("        void main() {");
document.writeln("");
document.writeln("          gl_Position = u_projection * a_position;");
document.writeln("          gl_PointSize = (10.0 / gl_Position.w) * 100.0;");
document.writeln("");
document.writeln("          v_color = a_color;");
document.writeln("");
document.writeln("        }`,");
document.writeln("      fragment: `");
document.writeln("        precision highp float;");
document.writeln("");
document.writeln("        uniform sampler2D u_texture;");
document.writeln("        uniform int u_hasTexture;");
document.writeln("");
document.writeln("        varying vec4 v_color;");
document.writeln("");
document.writeln("        void main() {");
document.writeln("");
document.writeln("          if ( u_hasTexture == 1 ) {");
document.writeln("");
document.writeln("            gl_FragColor = v_color * texture2D(u_texture, gl_PointCoord);");
document.writeln("");
document.writeln("          } else {");
document.writeln("");
document.writeln("            gl_FragColor = v_color;");
document.writeln("");
document.writeln("          }");
document.writeln("");
document.writeln("        }`,");
document.writeln("      uniforms: {},");
document.writeln("      buffers: {},");
document.writeln("      camera: {},");
document.writeln("      texture: null,");
document.writeln("      onUpdate: ( () => {} ),");
document.writeln("      onResize: ( () => {} ),");
document.writeln("    }, options )");
document.writeln("");
document.writeln("    const uniforms = Object.assign( {");
document.writeln("      time: { type: \'float\', value: 0 },");
document.writeln("      hasTexture: { type: \'int\', value: 0 },");
document.writeln("      resolution: { type: \'vec2\', value: [ 0, 0 ] },");
document.writeln("      mousemove: { type: \'vec2\', value: [ 0, 0 ] },");
document.writeln("      projection: { type: \'mat4\', value: [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ] },");
document.writeln("    }, options.uniforms )");
document.writeln("");
document.writeln("    const buffers = Object.assign( {");
document.writeln("      position: { size: 3, data: [] },");
document.writeln("      color: { size: 4, data: [] },");
document.writeln("    }, options.buffers )");
document.writeln("");
document.writeln("    const camera = Object.assign( {");
document.writeln("      fov: 60,");
document.writeln("      near: 1,");
document.writeln("      far: 10000,");
document.writeln("      aspect: 1,");
document.writeln("      z: 100,");
document.writeln("      perspective: true,");
document.writeln("    }, options.camera )");
document.writeln("");
document.writeln("    const canvas = document.createElement( \'canvas\' )");
document.writeln("    const gl = canvas.getContext( \'webgl\', { antialias: options.antialias } )");
document.writeln("");
document.writeln("    if ( ! gl ) return false");
document.writeln("");
document.writeln("    this.count = 0");
document.writeln("    this.gl = gl");
document.writeln("    this.canvas = canvas");
document.writeln("    this.camera = camera");
document.writeln("    this.holder = holder");
document.writeln("    this.onUpdate = options.onUpdate");
document.writeln("    this.onResize = options.onResize");
document.writeln("    this.data = {}");
document.writeln("");
document.writeln("    holder.appendChild( canvas )");
document.writeln("");
document.writeln("    this.createProgram( options.vertex, options.fragment )");
document.writeln("");
document.writeln("    this.createBuffers( buffers )");
document.writeln("    this.createUniforms( uniforms )");
document.writeln("");
document.writeln("    this.updateBuffers()");
document.writeln("    this.updateUniforms()");
document.writeln("");
document.writeln("    this.createTexture( options.texture )");
document.writeln("");
document.writeln("    gl.enable( gl.BLEND )");
document.writeln("    gl.enable( gl.CULL_FACE )");
document.writeln("    gl.blendFunc( gl.SRC_ALPHA, gl.ONE )");
document.writeln("    gl[ options.depthTest ? \'enable\' : \'disable\' ]( gl.DEPTH_TEST )");
document.writeln("");
document.writeln("    if ( options.autosize )");
document.writeln("      window.addEventListener( \'resize\', e => this.resize( e ), false )");
document.writeln("    if ( options.mousemove )");
document.writeln("      window.addEventListener( \'mousemove\', e => this.mousemove( e ), false )");
document.writeln("");
document.writeln("    this.resize()");
document.writeln("");
document.writeln("    this.update = this.update.bind( this )");
document.writeln("    this.time = { start: performance.now(), old: performance.now() }");
document.writeln("    this.update()");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  mousemove( e ) {");
document.writeln("");
document.writeln("    let x = e.pageX / this.width * 2 - 1");
document.writeln("    let y = e.pageY / this.height * 2 - 1");
document.writeln("");
document.writeln("    this.uniforms.mousemove = [ x, y ]");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  resize( e ) {");
document.writeln("");
document.writeln("    const holder = this.holder");
document.writeln("    const canvas = this.canvas");
document.writeln("    const gl = this.gl");
document.writeln("");
document.writeln("    const width = this.width = holder.offsetWidth");
document.writeln("    const height = this.height = holder.offsetHeight");
document.writeln("    const aspect = this.aspect = width / height");
document.writeln("    const dpi = this.dpi = devicePixelRatio");
document.writeln("");
document.writeln("    canvas.width = width * dpi");
document.writeln("    canvas.height = height * dpi");
document.writeln("    canvas.style.width = width + \'px\'");
document.writeln("    canvas.style.height = height + \'px\'");
document.writeln("");
document.writeln("    gl.viewport( 0, 0, width * dpi, height * dpi )");
document.writeln("    gl.clearColor( 0, 0, 0, 0 )");
document.writeln("");
document.writeln("    this.uniforms.resolution = [ width, height ]");
document.writeln("    this.uniforms.projection = this.setProjection( aspect )");
document.writeln("");
document.writeln("    this.onResize( width, height, dpi )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  setProjection( aspect ) {");
document.writeln("");
document.writeln("    const camera = this.camera");
document.writeln("");
document.writeln("    if ( camera.perspective ) {");
document.writeln("");
document.writeln("      camera.aspect = aspect");
document.writeln("");
document.writeln("      const fovRad = camera.fov * ( Math.PI / 180 )");
document.writeln("      const f = Math.tan( Math.PI * 0.5 - 0.5 * fovRad )");
document.writeln("      const rangeInv = 1.0 / ( camera.near - camera.far )");
document.writeln("");
document.writeln("      const matrix = [");
document.writeln("        f / camera.aspect, 0, 0, 0,");
document.writeln("        0, f, 0, 0,");
document.writeln("        0, 0, (camera.near + camera.far) * rangeInv, -1,");
document.writeln("        0, 0, camera.near * camera.far * rangeInv * 2, 0");
document.writeln("      ]");
document.writeln("");
document.writeln("      matrix[ 14 ] += camera.z");
document.writeln("      matrix[ 15 ] += camera.z");
document.writeln("");
document.writeln("      return matrix");
document.writeln("");
document.writeln("    } else {");
document.writeln("");
document.writeln("      return [");
document.writeln("         2 / this.width, 0, 0, 0,");
document.writeln("         0, -2 / this.height, 0, 0,");
document.writeln("         0, 0, 1, 0,");
document.writeln("        -1, 1, 0, 1,");
document.writeln("      ]");
document.writeln("");
document.writeln("    }");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createShader( type, source ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const shader = gl.createShader( type )");
document.writeln("");
document.writeln("    gl.shaderSource( shader, source )");
document.writeln("    gl.compileShader( shader )");
document.writeln("");
document.writeln("    if ( gl.getShaderParameter (shader, gl.COMPILE_STATUS ) ) {");
document.writeln("");
document.writeln("      return shader");
document.writeln("");
document.writeln("    } else {");
document.writeln("");
document.writeln("      console.log( gl.getShaderInfoLog( shader ) )");
document.writeln("      gl.deleteShader( shader )");
document.writeln("");
document.writeln("    }");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createProgram( vertex, fragment ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("");
document.writeln("    const vertexShader = this.createShader( gl.VERTEX_SHADER, vertex )");
document.writeln("    const fragmentShader = this.createShader( gl.FRAGMENT_SHADER, fragment )");
document.writeln("");
document.writeln("    const program = gl.createProgram()");
document.writeln("");
document.writeln("    gl.attachShader( program, vertexShader )");
document.writeln("    gl.attachShader( program, fragmentShader )");
document.writeln("    gl.linkProgram( program )");
document.writeln("");
document.writeln("    if ( gl.getProgramParameter( program, gl.LINK_STATUS ) ) {");
document.writeln("");
document.writeln("      gl.useProgram( program )");
document.writeln("      this.program = program");
document.writeln("");
document.writeln("    } else {");
document.writeln("");
document.writeln("      console.log( gl.getProgramInfoLog( program ) )");
document.writeln("      gl.deleteProgram( program )");
document.writeln("");
document.writeln("    }");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createUniforms( data ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const uniforms = this.data.uniforms = data");
document.writeln("    const values = this.uniforms = {}");
document.writeln("");
document.writeln("    Object.keys( uniforms ).forEach( name => {");
document.writeln("");
document.writeln("      const uniform = uniforms[ name ]");
document.writeln("");
document.writeln("      uniform.location = gl.getUniformLocation( this.program, \'u_\' + name )");
document.writeln("");
document.writeln("      Object.defineProperty( values, name, {");
document.writeln("        set: value => {");
document.writeln("");
document.writeln("          uniforms[ name ].value = value");
document.writeln("          this.setUniform( name, value )");
document.writeln("");
document.writeln("        },");
document.writeln("        get: () => uniforms[ name ].value");
document.writeln("      } )");
document.writeln("");
document.writeln("    } )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  setUniform( name, value ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const uniform = this.data.uniforms[ name ]");
document.writeln("");
document.writeln("    uniform.value = value");
document.writeln("");
document.writeln("    switch ( uniform.type ) {");
document.writeln("      case \'int\': {");
document.writeln("        gl.uniform1i( uniform.location, value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'float\': {");
document.writeln("        gl.uniform1f( uniform.location, value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'vec2\': {");
document.writeln("        gl.uniform2f( uniform.location, ...value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'vec3\': {");
document.writeln("        gl.uniform3f( uniform.location, ...value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'vec4\': {");
document.writeln("        gl.uniform4f( uniform.location, ...value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'mat2\': {");
document.writeln("        gl.uniformMatrix2fv( uniform.location, false, value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'mat3\': {");
document.writeln("        gl.uniformMatrix3fv( uniform.location, false, value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("      case \'mat4\': {");
document.writeln("        gl.uniformMatrix4fv( uniform.location, false, value )");
document.writeln("        break");
document.writeln("      }");
document.writeln("    }");
document.writeln("");
document.writeln("    // ivec2       : uniform2i,");
document.writeln("    // ivec3       : uniform3i,");
document.writeln("    // ivec4       : uniform4i,");
document.writeln("    // sampler2D   : uniform1i,");
document.writeln("    // samplerCube : uniform1i,");
document.writeln("    // bool        : uniform1i,");
document.writeln("    // bvec2       : uniform2i,");
document.writeln("    // bvec3       : uniform3i,");
document.writeln("    // bvec4       : uniform4i,");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  updateUniforms() {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const uniforms = this.data.uniforms");
document.writeln("");
document.writeln("    Object.keys( uniforms ).forEach( name => {");
document.writeln("");
document.writeln("      const uniform = uniforms[ name ]");
document.writeln("");
document.writeln("      this.uniforms[ name ] = uniform.value");
document.writeln("");
document.writeln("    } )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createBuffers( data ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const buffers = this.data.buffers = data");
document.writeln("    const values = this.buffers = {}");
document.writeln("");
document.writeln("    Object.keys( buffers ).forEach( name => {");
document.writeln("");
document.writeln("      const buffer = buffers[ name ]");
document.writeln("");
document.writeln("      buffer.buffer = this.createBuffer( \'a_\' + name, buffer.size )");
document.writeln("");
document.writeln("      Object.defineProperty( values, name, {");
document.writeln("        set: data => {");
document.writeln("");
document.writeln("          buffers[ name ].data = data");
document.writeln("          this.setBuffer( name, data )");
document.writeln("");
document.writeln("          if ( name == \'position\' )");
document.writeln("            this.count = buffers.position.data.length / 3");
document.writeln("");
document.writeln("        },");
document.writeln("        get: () => buffers[ name ].data");
document.writeln("      } )");
document.writeln("");
document.writeln("    } )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createBuffer( name, size ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const program = this.program");
document.writeln("");
document.writeln("    const index = gl.getAttribLocation( program, name )");
document.writeln("    const buffer = gl.createBuffer()");
document.writeln("");
document.writeln("    gl.bindBuffer( gl.ARRAY_BUFFER, buffer )");
document.writeln("    gl.enableVertexAttribArray( index )");
document.writeln("    gl.vertexAttribPointer( index, size, gl.FLOAT, false, 0, 0 )");
document.writeln("");
document.writeln("    return buffer");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  setBuffer( name, data ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const buffers = this.data.buffers");
document.writeln("");
document.writeln("    if ( name == null && ! gl.bindBuffer( gl.ARRAY_BUFFER, null ) ) return");
document.writeln("");
document.writeln("    gl.bindBuffer( gl.ARRAY_BUFFER, buffers[ name ].buffer )");
document.writeln("    gl.bufferData( gl.ARRAY_BUFFER, new Float32Array( data ), gl.STATIC_DRAW )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  updateBuffers() {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const buffers = this.buffers");
document.writeln("");
document.writeln("    Object.keys( buffers ).forEach( name =>");
document.writeln("      buffers[ name ] = buffer.data");
document.writeln("    )");
document.writeln("");
document.writeln("    this.setBuffer( null )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  createTexture( src ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const texture = gl.createTexture()");
document.writeln("");
document.writeln("    gl.bindTexture( gl.TEXTURE_2D, texture )");
document.writeln("    gl.texImage2D( gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array( [ 0, 0, 0, 0 ] ) )");
document.writeln("");
document.writeln("    this.texture = texture");
document.writeln("");
document.writeln("    if ( src ) {");
document.writeln("");
document.writeln("      this.uniforms.hasTexture = 1");
document.writeln("      this.loadTexture( src )");
document.writeln("");
document.writeln("    }");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  loadTexture( src ) {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("    const texture = this.texture");
document.writeln("");
document.writeln("    const textureImage = new Image()");
document.writeln("");
document.writeln("    textureImage.onload = () => {");
document.writeln("");
document.writeln("      gl.bindTexture( gl.TEXTURE_2D, texture )");
document.writeln("");
document.writeln("      gl.texImage2D( gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, textureImage )");
document.writeln("");
document.writeln("      gl.texParameteri( gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR )");
document.writeln("      gl.texParameteri( gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR )");
document.writeln("");
document.writeln("      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE)");
document.writeln("      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE)");
document.writeln("");
document.writeln("      // gl.generateMipmap( gl.TEXTURE_2D )");
document.writeln("");
document.writeln("    }");
document.writeln("");
document.writeln("    textureImage.src = src");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("  update() {");
document.writeln("");
document.writeln("    const gl = this.gl");
document.writeln("");
document.writeln("    const now = performance.now()");
document.writeln("    const elapsed = ( now - this.time.start ) / 5000");
document.writeln("    const delta = now - this.time.old");
document.writeln("    this.time.old = now");
document.writeln("");
document.writeln("    this.uniforms.time = elapsed");
document.writeln("");
document.writeln("    if ( this.count > 0 ) {");
document.writeln("      gl.clear( gl.COLORBUFFERBIT )");
document.writeln("      gl.drawArrays( gl.POINTS, 0, this.count )");
document.writeln("    }");
document.writeln("");
document.writeln("    this.onUpdate( delta )");
document.writeln("");
document.writeln("    requestAnimationFrame( this.update )");
document.writeln("");
document.writeln("  }");
document.writeln("");
document.writeln("}");
document.writeln("");
document.writeln("const pointSize = 2.5");
document.writeln("");
document.writeln("const waves = new ShaderProgram( document.querySelector( \'.waves\' ), {");
document.writeln("  texture: \'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAb1BMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8v0wLRAAAAJHRSTlMAC/goGvDhmwcExrVjWzrm29TRqqSKenRXVklANSIUE8mRkGpv+HOfAAABCElEQVQ4y4VT13LDMAwLrUHteO+R9f/fWMfO6dLaPeKVEECRxOULWsEGpS9nULDwia2Y+ALqUNbAWeg775zv+sA4/FFRMxt8U2FZFCVWjR/YrH4/H9sarclSKdPMWKzb8VsEeHB3m0shkhVCyNzeXeAQ9Xl4opEieX2QCGnwGbj6GMyjw9t1K0fK9YZunPXeAGsfJtYjwzxaBnozGGorYz0ypK2HzQSYx1y8DgSRo2ewOiyh2QWOEk1Y9OrQV0a8TiBM1a8eMHWYnRMy7CZ4t1CmyRkhSUvP3gRXyHOCLBxNoC3IJv//ZrJ/kxxUHPUB+6jJZZHrpg6GOjnqaOmzp4NDR48OLxn/H27SRQ08S0ZJAAAAAElFTkSuQmCC\',");
document.writeln("  uniforms: {");
document.writeln("    size: { type: \'float\', value: pointSize },");
document.writeln("    field: { type: \'vec3\', value: [ 0, 0, 0 ] },");
document.writeln("    speed: { type: \'float\', value: 5 },");
document.writeln("  },");
document.writeln("  vertex: `");
document.writeln("    #define M_PI 3.1415926535897932384626433832795");
document.writeln("");
document.writeln("    precision highp float;");
document.writeln("");
document.writeln("    attribute vec4 a_position;");
document.writeln("    attribute vec4 a_color;");
document.writeln("");
document.writeln("    uniform float u_time;");
document.writeln("    uniform float u_size;");
document.writeln("    uniform float u_speed;");
document.writeln("    uniform vec3 u_field;");
document.writeln("    uniform mat4 u_projection;");
document.writeln("");
document.writeln("    varying vec4 v_color;");
document.writeln("");
document.writeln("    void main() {");
document.writeln("");
document.writeln("      vec3 pos = a_position.xyz;");
document.writeln("");
document.writeln("      pos.y += (");
document.writeln("        cos(pos.x / u_field.x * M_PI * 8.0 + u_time * u_speed) +");
document.writeln("        sin(pos.z / u_field.z * M_PI * 8.0 + u_time * u_speed)");
document.writeln("      ) * u_field.y;");
document.writeln("");
document.writeln("      gl_Position = u_projection * vec4( pos.xyz, a_position.w );");
document.writeln("      gl_PointSize = ( u_size / gl_Position.w ) * 100.0;");
document.writeln("");
document.writeln("      v_color = a_color;");
document.writeln("");
document.writeln("    }`,");
document.writeln("  fragment: `");
document.writeln("    precision highp float;");
document.writeln("");
document.writeln("    uniform sampler2D u_texture;");
document.writeln("");
document.writeln("    varying vec4 v_color;");
document.writeln("");
document.writeln("    void main() {");
document.writeln("");
document.writeln("      gl_FragColor = v_color * texture2D(u_texture, gl_PointCoord);");
document.writeln("");
document.writeln("    }`,");
document.writeln("  onResize( w, h, dpi ) {");
document.writeln("");
document.writeln("    const position = [], color = []");
document.writeln("");
document.writeln("    const width = 400 * ( w / h )");
document.writeln("    const depth = 400");
document.writeln("    const height = 3");
document.writeln("    const distance = 5");
document.writeln("");
document.writeln("    for ( let x = 0; x < width; x += distance ) {");
document.writeln("      for ( let z = 0; z < depth; z+= distance ) {");
document.writeln("");
document.writeln("        position.push( - width / 2 + x, -30, -depth / 2 + z )");
document.writeln("        color.push( 0, 1 - ( x / width ) * 1, 0.5 + x / width * 0.5, z / depth )");
document.writeln("");
document.writeln("      }");
document.writeln("    }");
document.writeln("");
document.writeln("    this.uniforms.field = [ width, height, depth ]");
document.writeln("");
document.writeln("    this.buffers.position = position");
document.writeln("    this.buffers.color = color");
document.writeln("");
document.writeln("    this.uniforms.size = ( h / 400) * pointSize * dpi");
document.writeln("");
document.writeln("  },");
document.writeln("} )");
document.writeln("</script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");